/**
 * src/badwords.js
 * Substring-based username filter.
 * Any username containing one of these strings (case-insensitive) is rejected.
 * Add new entries to the array below — they are checked at registration time.
 */

const BAD_WORDS = [
  "2g1c", "2girls1cup", "4r5e", "5h1t", "5hit", "a2m", "a54", "admin",
  "administrator", "aeolus", "ahole", "alabamahotpocket", "alaskanpipeline", "anal", "analannie", "analimpaler",
  "analleakage", "analprobe", "analsex", "anilingus", "anus", "apeshit", "ar5e", "areola",
  "areole", "arian", "arrse", "arse", "arsehole", "aryan", "ass", "assbag",
  "assbagger", "assbandit", "assbang", "assbanged", "assbanger", "assbangs", "assbite", "assblaster",
  "assclown", "asscock", "asscracker", "asses", "assface", "assfaces", "assfuck", "assfucker",
  "assfukka", "assgoblin", "assh0le", "asshat", "asshead", "assho1e", "asshole", "assholes",
  "asshopper", "asshore", "assjabber", "assjacker", "assjockey", "asskiss", "asskisser", "assklown",
  "asslick", "asslicker", "asslover", "assman", "assmaster", "assmonkey", "assmucus", "assmunch",
  "assmuncher", "assnigger", "asspacker", "asspirate", "asspuppies", "assranger", "assshit", "assshole",
  "asssucker", "asswad", "asswhole", "asswhore", "asswipe", "asswipes", "autoerotic", "axwound",
  "azz", "b17ch", "b1tch", "babybatter", "babyjuice", "badfuck", "ballbag", "ballgag",
  "ballgravy", "ballkicking", "balllicker", "balllicking", "ballsack", "ballsucking", "bampot", "bangbros",
  "banned", "bareback", "barelylegal", "barface", "barfface", "bastard", "bastardo", "bastards",
  "bastinado", "battyboy", "bawdy", "bazongas", "bazooms", "bdsm", "beaner", "beaners",
  "beardedclam", "beastial", "beastiality", "beatch", "beatyourmeat", "beaver", "beavercleaver", "beaverlips",
  "beefcurtain", "beefcurtains", "beeyotch", "bellend", "bender", "beotch", "bestial", "bestiality",
  "biatch", "bigbastard", "bigblack", "bigbreasts", "bigbutt", "bigknockers", "bigtits", "bimbo",
  "bimbos", "bint", "birdlock", "bitch", "bitchass", "bitched", "bitcher", "bitchers",
  "bitches", "bitchez", "bitchin", "bitching", "bitchtit", "bitchtits", "bitchy", "blackcock",
  "blacksupr", "bloodclaat", "blowjob", "blowme", "blowmud", "blowyourload", "bluewaffle", "blumpkin",
  "boang", "bohunk", "boink", "boiolas", "bollick", "bollock", "bollocks", "bollok",
  "bollox", "bomber", "bondage", "boner", "boners", "boob", "boobies", "boobs",
  "booby", "boong", "boonga", "booobs", "boooobs", "booooobs", "booooooobs", "bootee",
  "bootie", "booty", "bootycall", "bosom", "bosomy", "breast", "breastjob", "breastlover",
  "breastman", "breasts", "brotherfucker", "brownshowers", "brunetteaction", "buceta", "bugger", "buggered",
  "buggery", "bukkake", "bullcrap", "bulldike", "bulldyke", "bulletvibe", "bullshit", "bullshits",
  "bullshitted", "bullturds", "bumblefuck", "bumboy", "bumclat", "bumfuck", "bung", "bunga",
  "bunghole", "bunnyfucker", "bustaload", "busty", "butchdike", "butchdyke", "butt", "buttbang",
  "buttcheeks", "buttface", "buttfuck", "buttfucka", "buttfucker", "butthead", "butthole", "buttman",
  "buttmuch", "buttmunch", "buttmuncher", "buttpirate", "buttplug", "caca", "cahone", "cameltoe",
  "camgirl", "camslut", "camwhore", "carpetmuncher", "cawk", "cheater", "chesticle", "chichiman",
  "chickwithadick", "childfucker", "chinc", "chincs", "chink", "chinky", "choad", "choade",
  "chocice", "chocolaterosebuds", "chode", "chodes", "chotabags", "cipa", "circlejerk", "cl1t",
  "clevelandsteamer", "climax", "clit", "clitface", "clitfuck", "clitlicker", "clitoris", "clitorus",
  "clits", "clitty", "clittylitter", "clogwog", "cloverclamps", "clunge", "clusterfuck", "cnut",
  "cocain", "cocaine", "cock", "cockass", "cockbite", "cockblock", "cockburger", "cockeye",
  "cockface", "cockfucker", "cockhead", "cockholster", "cockjockey", "cockknocker", "cockknoker", "cocklicker",
  "cocklover", "cocklump", "cockmaster", "cockmongler", "cockmongruel", "cockmonkey", "cockmunch", "cockmuncher",
  "cocknose", "cocknugget", "cockpocket", "cocks", "cockshit", "cocksmith", "cocksmoke", "cocksmoker",
  "cocksniffer", "cocksnot", "cocksucer", "cocksuck", "cocksucked", "cocksucker", "cocksuckers", "cocksucking",
  "cocksucks", "cocksuka", "cocksukka", "cockwaffle", "coital", "cok", "cokmuncher", "coksucka",
  "commie", "condom", "coochie", "coochy", "coon", "coonnass", "coons", "cooter",
  "coprolagnia", "coprophilia", "corksucker", "cornhole", "crabs", "cracker", "crackwhore", "crap",
  "crappy", "creampie", "cum", "cumbubble", "cumchugger", "cumdump", "cumdumpster", "cumfreak",
  "cumguzzler", "cumjockey", "cummer", "cummin", "cumming", "cums", "cumshot", "cumshots",
  "cumslut", "cumstain", "cumtart", "cunilingus", "cunillingus", "cunnilingus", "cunntt", "cunny",
  "cunt", "cuntass", "cuntbag", "cuntface", "cuntfuck", "cuntfucker", "cunthair", "cunthole",
  "cunthunter", "cuntlick", "cuntlicker", "cuntlicking", "cuntrag", "cunts", "cuntsicle", "cuntslut",
  "cuntstruck", "cuntsucker", "cutter", "cyberfuck", "cyberfucked", "cyberfucker", "cyberfuckers", "cyberfucking",
  "cybersex", "dago", "dagos", "darkie", "daterape", "dawgiestyle", "deepthroat", "deggo",
  "dendrophilia", "dick", "dickbag", "dickbeaters", "dickbrain", "dickdipper", "dickface", "dickflipper",
  "dickfuck", "dickfucker", "dickhead", "dickheads", "dickhole", "dickish", "dickjuice", "dickmilk",
  "dickmonger", "dickripper", "dicks", "dickshy", "dicksipper", "dickslap", "dicksneeze", "dicksucker",
  "dicksucking", "dicktickler", "dickwad", "dickweasel", "dickweed", "dickwhipper", "dickwod", "dickzipper",
  "diddle", "dike", "dildo", "dildos", "diligaf", "dingle", "dingleberries", "dingleberry",
  "dink", "dinks", "dipshit", "dirtypillows", "dirtysanchez", "dogfucker", "doggiestyle", "doggin",
  "dogging", "doggystyle", "dolcett", "dominatrix", "dommes", "dong", "donkeypunch", "donkeyribber",
  "doochbag", "doubledong", "doublepenetration", "douche", "douchebag", "douchebags", "douchefag", "douchewaffle",
  "dpaction", "dryhump", "dumass", "dumbass", "dumbasses", "dumbcunt", "dumbfuck", "dumbshit",
  "dvda", "dyke", "dykes", "eatadick", "eathairpie", "eatmyass", "eatpussy", "ejaculate",
  "ejaculated", "ejaculates", "ejaculating", "ejaculation", "ejakulate", "erection", "erotic", "erotism",
  "eunuch", "extremist", "facefucker", "facial", "fag", "fagbag", "fagfucker", "fagg",
  "fagged", "fagging", "faggit", "faggitt", "faggot", "faggotcock", "faggots", "faggs",
  "fagot", "fagots", "fags", "fagtard", "faig", "faigt", "fanny", "fannybandit",
  "fannyflaps", "fannyfucker", "fart", "fartknocker", "fastfuck", "fatass", "fatfuck", "fatfucker",
  "fcuk", "fcuker", "fcuking", "fecal", "feck", "fecker", "felch", "felcher",
  "felching", "fellate", "fellatio", "feltch", "feltcher", "femalesquirting", "femdom", "figging",
  "fingerbang", "fingerfuck", "fingerfucked", "fingerfucker", "fingerfuckers", "fingerfucking", "fingerfucks", "fingering",
  "fisted", "fistfuck", "fistfucked", "fistfucker", "fistfuckers", "fistfucking", "fistfuckings", "fistfucks",
  "fisting", "fisty", "flamer", "flange", "fleshflute", "flogthelog", "floozy", "fondle",
  "footfetish", "footfuck", "footfucker", "footjob", "footlicker", "foreskin", "freakfuck", "freakyfucker",
  "freefuck", "frigg", "frigga", "frotting", "fubar", "fuck", "fucka", "fuckass",
  "fuckbag", "fuckbitch", "fuckboy", "fuckbrain", "fuckbutt", "fuckbutter", "fuckbuttons", "fucked",
  "fucker", "fuckers", "fuckersucker", "fuckface", "fuckfreak", "fuckhead", "fuckheads", "fuckher",
  "fuckhole", "fuckin", "fucking", "fuckingbitch", "fuckings", "fuckme", "fuckmeat", "fuckmehard",
  "fuckmonkey", "fucknugget", "fucknut", "fucknutt", "fuckoff", "fuckpuppet", "fucks", "fuckstick",
  "fucktard", "fucktards", "fucktart", "fucktoy", "fucktrophy", "fucktwat", "fuckup", "fuckwad",
  "fuckwhit", "fuckwhore", "fuckwit", "fuckwitt", "fuckyou", "fudgepacker", "fuk", "fuker",
  "fukker", "fukkers", "fukkin", "fuks", "fukwhit", "fukwit", "fuq", "futanari",
  "fux", "fux0r", "fvck", "fxck", "gangbang", "gangbanged", "gangbangs", "ganja",
  "gash", "gayass", "gaybob", "gaydo", "gayfuck", "gayfuckist", "gaylord", "gaysex",
  "gaytard", "gaywad", "genitals", "genocide", "goatcx", "goatse", "godamn", "godamnit",
  "goddam", "goddammit", "goddamn", "goddamnit", "goddamnmuthafucker", "godsdamn", "gokkun", "goldenshower",
  "golliwog", "gonad", "gonads", "gook", "gooks", "goregasm", "gotohell", "griefer",
  "gringo", "grope", "groupsex", "gspot", "guest", "guido", "guro", "hacker",
  "hamflap", "handjob", "hardcore", "hardcoresex", "hardon", "hatefag", "hatefuck", "hatespeech",
  "headfuck", "hebe", "heeb", "hentai", "heroin", "herpes", "heshe", "hitler",
  "hiv", "hoar", "hoare", "hobag", "hoer", "holocaust", "holyshit", "homo",
  "homodumbshit", "homoerotic", "homoey", "honkey", "honky", "hookah", "hooker", "hoor",
  "hooter", "hooters", "hore", "horniest", "horny", "hotcarl", "hotchick", "hotpussy",
  "hotsex", "howtokill", "howtomurder", "hugefat", "humped", "humping", "hussy", "hymen",
  "iberianslap", "inbred", "incest", "injun", "intercourse", "jackass", "jackasses", "jackhole",
  "jackoff", "jailbait", "jap", "japs", "jellydonut", "jerkass", "jerked", "jerkoff",
  "jigaboo", "jiggaboo", "jiggerboo", "jihadi", "jism", "jiz", "jizm", "jizz",
  "jizzed", "juggs", "junglebunny", "junkie", "junky", "kafir", "kawk", "kike",
  "kikes", "kinbaku", "kinkster", "kinky", "kkk", "kkkmember", "klan", "knobbing",
  "knobead", "knobed", "knobend", "knobhead", "knobjocky", "knobjokey", "kock", "kooch",
  "kooches", "kootch", "kum", "kummer", "kumming", "kums", "kunilingus", "kunt",
  "kwif", "kyke", "labia", "lameass", "lardass", "leatherrestraint", "lemonparty", "lesbo",
  "lesbos", "lez", "lezbian", "lezbians", "lezbo", "lezbos", "lezza", "lezzie",
  "lezzies", "lezzy", "lolita", "lovemaking", "lynching", "mafugly", "makemecome", "malesquirting",
  "masochist", "masterb8", "masterbat", "masterbat3", "masterbate", "masterbating", "masterbation", "masterbations",
  "masturbate", "masturbating", "masturbation", "mcfagget", "menageatrois", "mick", "middlefinger", "midget",
  "milf", "minge", "minger", "missionaryposition", "moderator", "mofo", "molest", "moolie",
  "moomoofoofoo", "mothafuck", "mothafucka", "mothafuckas", "mothafuckaz", "mothafucked", "mothafucker", "mothafuckers",
  "mothafuckin", "mothafucking", "mothafucks", "motherfuck", "motherfucka", "motherfucked", "motherfucker", "motherfuckers",
  "motherfuckin", "motherfucking", "motherfuckings", "motherfuckka", "motherfucks", "moundofvenus", "mrhands", "muff",
  "muffdiver", "muffdiving", "muffpuff", "munging", "munter", "mutha", "muthafecker", "muthafuckaz",
  "muthafuckker", "muther", "mutherfucker", "mutherfucking", "muthrfucking", "nads", "nambla", "napalm",
  "nappy", "nawashi", "nazi", "nazism", "negro", "neonazi", "nigaboo", "nigga",
  "niggah", "niggas", "niggaz", "nigger", "niggers", "niglet", "nignog", "nimphomania",
  "nimrod", "nipple", "nipples", "nobhead", "nobjocky", "nobjokey", "noname", "nonce",
  "nooky", "nude", "nudity", "numbnuts", "nutbutter", "nutsack", "nutter", "nympho",
  "nymphomania", "octopussy", "official", "oldbag", "omorashi", "onecuptwogirls", "oneguyonejar", "orally",
  "orgasim", "orgasims", "orgasm", "orgasmic", "orgasms", "orgies", "orgy", "osama",
  "ovary", "ovum", "owner", "paedophile", "paki", "panooch", "pantie", "panties",
  "panty", "pecker", "peckerhead", "pedo", "pedobear", "pedophile", "pedophilia", "pedophiliac",
  "pegging", "penetrate", "penetration", "penial", "penile", "penis", "penisbanger", "penisfucker",
  "penispuffer", "perversion", "peyote", "phalli", "phallic", "phonesex", "phuck", "phuk",
  "phuked", "phuking", "phukked", "phukking", "phuks", "phuq", "pieceofshit", "pigfucker",
  "pillowbiter", "pimp", "pimpis", "pinko", "piss", "pissed", "pissedoff", "pisser",
  "pissers", "pisses", "pissflaps", "pissin", "pissing", "pissoff", "pisspig", "polesmoker",
  "ponyplay", "poon", "poonani", "poonany", "poontang", "poop", "poopchute", "poopuncher",
  "porchmonkey", "porn", "porno", "pornography", "pornos", "prick", "pricks", "prickteaser",
  "princealbertpiercing", "pron", "prostitute", "pthc", "pube", "pubes", "pubic", "pubis",
  "punani", "punanny", "punany", "punkass", "punta", "puss", "pusse", "pussi",
  "pussies", "pussy", "pussyfart", "pussylicking", "pussypalace", "pussypounder", "pussys", "puto",
  "queaf", "queef", "queer", "queerbait", "queerhole", "queero", "queers", "quim",
  "raghead", "ragingboner", "rape", "raped", "raper", "rapey", "raping", "rapist",
  "raunch", "rectal", "rectum", "rectus", "reetard", "reich", "retard", "retarded",
  "reversecowgirl", "rimjaw", "rimjob", "rimming", "root", "rosypalm", "rustytrombone", "sadism",
  "sadist", "sambo", "sandnigger", "sanger", "santorum", "sausagequeen", "scammer", "scat",
  "schizo", "schlong", "scissoring", "screwed", "screwing", "scroat", "scrog", "scrot",
  "scrote", "scrotum", "seaman", "seamen", "seduce", "selfharm", "semen", "sex",
  "sexo", "sexual", "shag", "shagger", "shaggin", "shagging", "shamedame", "shavedbeaver",
  "shavedpussy", "shemale", "shibari", "shit", "shitass", "shitbag", "shitbagger", "shitblimp",
  "shitbrains", "shitbreath", "shitcanned", "shitcunt", "shitdick", "shite", "shiteater", "shited",
  "shitface", "shitfaced", "shitfuck", "shitfucker", "shitfull", "shithead", "shitheads", "shithole",
  "shithouse", "shiting", "shits", "shitspitter", "shitstain", "shitt", "shitted", "shitter",
  "shitters", "shittier", "shittiest", "shitting", "shitty", "shiz", "shiznit", "shooter",
  "shota", "shrimping", "skag", "skank", "skeet", "skullfuck", "slag", "slanteye",
  "slave", "sleaze", "sleazy", "slut", "slutbag", "slutbucket", "slutdumper", "slutkiss",
  "sluts", "smartass", "smartasses", "smegma", "smut", "smutty", "snatch", "snowballing",
  "snuff", "sodoff", "sodom", "sodomize", "sodomy", "sonofabitch", "sonofawhore", "spammer",
  "sperm", "spic", "spick", "spik", "spiks", "splooge", "sploogemoose", "spooge",
  "spook", "spreadlegs", "spunk", "staff", "stalin", "stfu", "strapon", "strappado",
  "stripclub", "suicide", "suicidegirls", "sultrywomen", "sumofabiatch", "superuser", "support", "supremacist",
  "swastika", "swinger", "sysadmin", "system", "taig", "taintedlove", "takingthepiss", "tampon",
  "tard", "tastemy", "tawdry", "teabagging", "teat", "teets", "terd", "terrorist",
  "teste", "testee", "testes", "testical", "testicle", "testis", "threesome", "throating",
  "thundercunt", "tinkle", "tit", "titfuck", "titi", "tities", "tits", "titt",
  "tittie5", "tittiefucker", "titties", "titty", "tittyfuck", "tittyfucker", "tittywank", "titwank",
  "tosser", "towelhead", "tranny", "transsexual", "trashy", "tribadism", "tubgirl", "turd",
  "tush", "tushy", "tw4t", "twat", "twathead", "twatlips", "twats", "twatty",
  "twatwaffle", "twink", "twogirlsonecup", "twunt", "twunter", "unclefucker", "undressing", "upskirt",
  "urethraplay", "urophilia", "uterus", "vag", "vagina", "vajayjay", "vajj", "valium",
  "venusmound", "viagra", "vibrator", "violetwand", "vixen", "vjayjay", "vodka", "vorarephilia",
  "voyeur", "vulgar", "vulva", "wang", "wank", "wanker", "wankjob", "wanky",
  "wazoo", "weed", "weenie", "weewee", "weiner", "wench", "wetback", "wetdream",
  "wh0re", "wh0reface", "whitepower", "whitesupremacist", "whitey", "whoar", "whoralicious", "whore",
  "whorealicious", "whorebag", "whored", "whoreface", "whorehopper", "whorehouse", "whores", "whoring",
  "wigger", "willies", "willy", "windowlicker", "wiseass", "wiseasses", "wog", "woody",
  "wop", "wrinkledstarfish", "xrated", "xxx", "yaoi", "yellowshowers", "yid", "yiffy",
  "yobbo", "zoophile", "zoophilia",
];

/**
 * Returns true if the username contains any banned substring.
 * Strips non-alphanumeric chars first so "@ss" and "a.s.s" are also caught.
 */
export function containsBadWord(username) {
  const clean = username.toLowerCase().replace(/[^a-z0-9]/g, "");
  return BAD_WORDS.some(w => clean.includes(w));
}
